apiVersion: apps/v1
kind: Deployment
metadata:
  name: staycrest
spec:
  template:
    spec:
      containers:
      - name: staycrest
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi" 