receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'staycrest-metrics'
          scrape_interval: 15s
          static_configs:
            - targets: ['app:9091']
        - job_name: 'node-exporter'
          scrape_interval: 15s
          static_configs:
            - targets: ['node-exporter:9100']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  resource:
    attributes:
      - key: service.name
        value: staycrest-api
        action: upsert
      - key: deployment.environment
        value: ${ENVIRONMENT}
        action: upsert
  filter:
    spans:
      include:
        match_type: regexp
        services:
          - staycrest.*
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 100

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: staycrest
  file:
    path: /etc/otelcol/logs/traces.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [jaeger, otlp, logging, file]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed 