apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staycrest-prod

commonLabels:
  environment: production
  variant: prod

patches:
- path: replicas-patch.yaml
- path: resources-patch.yaml
- path: security-patch.yaml
- path: hpa-patch.yaml

configMapGenerator:
- name: staycrest-config
  behavior: merge
  literals:
    - NODE_ENV=production
    - LOG_LEVEL=info
    - WORKER_THREADS=4
    - ENABLE_METRICS=true
    - API_RATE_LIMIT=100
    - CACHE_TTL=3600
    - CONNECTION_POOL_SIZE=50
    # Search Sources Configuration
    - ENABLE_LOYALTY_PROGRAMS=true
    - ENABLE_WEB_SEARCH=true
    - ENABLE_HOTEL_AGGREGATORS=true
    - ENABLE_DIRECT_BOOKING=true
    # Database Cache Configuration
    - ENABLE_REDIS_CACHE=true
    - ENABLE_MONGODB_CACHE=true
    - ENABLE_POSTGRES_PGBOUNCER=true
    - ENABLE_POSTGRES_QUERY_CACHE=true
    - CACHE_STRATEGY=layered
    - DB_CACHE_METRICS=true
    - REDIS_MAX_MEMORY=2gb
    - MONGODB_QUERY_CACHE_SIZE=512mb
    - PGBOUNCER_MAX_CONNECTIONS=100
    - CACHE_CIRCUIT_BREAKER=true
    - CACHE_FALLBACK_STRATEGY=stale-while-revalidate 