apiVersion: apps/v1
kind: Deployment
metadata:
  name: staycrest
spec:
  template:
    spec:
      containers:
      - name: staycrest
        resources:
          limits:
            cpu: "2"
            memory: "3Gi"
          requests:
            cpu: "1"
            memory: "1.5Gi" 