apiVersion: apps/v1
kind: Deployment
metadata:
  name: staycrest
  labels:
    app: staycrest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: staycrest
  template:
    metadata:
      labels:
        app: staycrest
    spec:
      containers:
      - name: staycrest
        image: staycrest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: staycrest-secrets
              key: database-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: staycrest-secrets
              key: openai-api-key
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: staycrest-secrets
              key: session-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: staycrest-secrets
              key: jwt-secret
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: staycrest-service
  labels:
    app: staycrest
spec:
  selector:
    app: staycrest
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staycrest-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - staycrest.example.com
    secretName: staycrest-tls-secret
  rules:
  - host: staycrest.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: staycrest-service
            port:
              name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: staycrest-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: staycrest-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staycrest
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 